using Octokit;
using DeploymentService.Models;
using Microsoft.Extensions.Options;

namespace DeploymentService.Services;

public class GitHubService
{
    private readonly ILogger<GitHubService> _logger;
    private readonly GitHubClient _client;
    private readonly AppSettings _settings;

    public GitHubService(
        ILogger<GitHubService> logger,
        IOptions<AppSettings> settings)
    {
        _logger = logger;
        _settings = settings.Value;
        _client = new GitHubClient(new ProductHeaderValue("self-healing-k8s"))
        {
            Credentials = new Credentials(_settings.GitHubToken)
        };
    }

    public async Task<string?> OpenHealingPrAsync(HealingResult result)
    {
        try
        {
            var branchName = $"fix/self-healing-{result.OriginalFailure.Type}-{DateTime.UtcNow:yyyyMMddHHmmss}";

            var mainRef = await _client.Git.Reference.Get(
                _settings.GitHubRepoOwner,
                _settings.GitHubRepoName,
                "refs/heads/main");

            await _client.Git.Reference.Create(
                _settings.GitHubRepoOwner,
                _settings.GitHubRepoName,
                new NewReference($"refs/heads/{branchName}", mainRef.Object.Sha));

            _logger.LogInformation("Created branch {Branch}", branchName);

            var fixContent = BuildFixFile(result);
            var fileName = $"fixes/healing-{result.OriginalFailure.Type}-{DateTime.UtcNow:yyyyMMddHHmmss}.md";

            await _client.Repository.Content.CreateFile(
                _settings.GitHubRepoOwner,
                _settings.GitHubRepoName,
                fileName,
                new CreateFileRequest(
                    message: $"fix: self-healing patch for {result.OriginalFailure.Type} in {result.PodName}",
                    content: Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(fixContent)),
                    branch: branchName)
                {
                    Committer = new Committer("self-healing-k8s", "self-healing@github.com", DateTimeOffset.UtcNow)
                });

            _logger.LogInformation("Committed fix file to branch {Branch}", branchName);

            var prBody = BuildPrBody(result);

            var pr = await _client.PullRequest.Create(
                _settings.GitHubRepoOwner,
                _settings.GitHubRepoName,
                new NewPullRequest(
                    title: $"fix: self-healing patch for {result.OriginalFailure.Type} in {result.PodName}",
                    head: branchName,
                    baseRef: "main")
                {
                    Body = prBody
                });

            _logger.LogInformation("PR opened: {Url}", pr.HtmlUrl);
            return pr.HtmlUrl;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to open PR for {Pod}", result.PodName);
            return null;
        }
    }

    private string BuildFixFile(HealingResult result)
    {
        return $"""
            # Self-Healing Analysis Report

            **Pod:** {result.PodName}
            **Failure Type:** {result.OriginalFailure.Type}
            **Detected:** {result.OriginalFailure.DetectedAt:yyyy-MM-dd HH:mm:ss} UTC
            **Severity:** {result.Severity}

            ## Root Cause
            {result.RootCause}

            ## Suggested Fix
            {result.SuggestedFix}

            ## Code Fix
            {result.CodeFix}
            """;
    }

    private string BuildPrBody(HealingResult result)
    {
        return $"""
            ## Self-Healing Patch

            This PR was opened automatically by the self-healing-k8s system.

            ### Failure detected
            - **Pod:** {result.PodName}
            - **Namespace:** {result.OriginalFailure.Namespace}
            - **Type:** {result.OriginalFailure.Type}
            - **Detected at:** {result.OriginalFailure.DetectedAt:yyyy-MM-dd HH:mm:ss} UTC

            ### Root cause
            {result.RootCause}

            ### Severity
            {result.Severity}

            ### Suggested fix
            {result.SuggestedFix}

            ### Proposed code change
            {result.CodeFix}

            ---
            *Generated by [self-healing-k8s](https://github.com/{_settings.GitHubRepoOwner}/self-healing-k8s)*
            """;
    }
}